# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/cplus/object/learning/tmp/tmp.RpGd52Kree/learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/cplus/object/learning/tmp/tmp.RpGd52Kree/learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cplus/object/learning/tmp/tmp.RpGd52Kree/learning/CMakeFiles /home/ubuntu/cplus/object/learning/tmp/tmp.RpGd52Kree/learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cplus/object/learning/tmp/tmp.RpGd52Kree/learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named learning

# Build rule for target.
learning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 learning
.PHONY : learning

# fast build rule for target.
learning/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/build
.PHONY : learning/fast

CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o: cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i: cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s: cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

config/MysqlDb.o: config/MysqlDb.cpp.o
.PHONY : config/MysqlDb.o

# target to build an object file
config/MysqlDb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/config/MysqlDb.cpp.o
.PHONY : config/MysqlDb.cpp.o

config/MysqlDb.i: config/MysqlDb.cpp.i
.PHONY : config/MysqlDb.i

# target to preprocess a source file
config/MysqlDb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/config/MysqlDb.cpp.i
.PHONY : config/MysqlDb.cpp.i

config/MysqlDb.s: config/MysqlDb.cpp.s
.PHONY : config/MysqlDb.s

# target to generate assembly for a file
config/MysqlDb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/config/MysqlDb.cpp.s
.PHONY : config/MysqlDb.cpp.s

demo/p1/Polymorphism.o: demo/p1/Polymorphism.cpp.o
.PHONY : demo/p1/Polymorphism.o

# target to build an object file
demo/p1/Polymorphism.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p1/Polymorphism.cpp.o
.PHONY : demo/p1/Polymorphism.cpp.o

demo/p1/Polymorphism.i: demo/p1/Polymorphism.cpp.i
.PHONY : demo/p1/Polymorphism.i

# target to preprocess a source file
demo/p1/Polymorphism.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p1/Polymorphism.cpp.i
.PHONY : demo/p1/Polymorphism.cpp.i

demo/p1/Polymorphism.s: demo/p1/Polymorphism.cpp.s
.PHONY : demo/p1/Polymorphism.s

# target to generate assembly for a file
demo/p1/Polymorphism.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p1/Polymorphism.cpp.s
.PHONY : demo/p1/Polymorphism.cpp.s

demo/p2/Collections.o: demo/p2/Collections.cpp.o
.PHONY : demo/p2/Collections.o

# target to build an object file
demo/p2/Collections.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p2/Collections.cpp.o
.PHONY : demo/p2/Collections.cpp.o

demo/p2/Collections.i: demo/p2/Collections.cpp.i
.PHONY : demo/p2/Collections.i

# target to preprocess a source file
demo/p2/Collections.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p2/Collections.cpp.i
.PHONY : demo/p2/Collections.cpp.i

demo/p2/Collections.s: demo/p2/Collections.cpp.s
.PHONY : demo/p2/Collections.s

# target to generate assembly for a file
demo/p2/Collections.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p2/Collections.cpp.s
.PHONY : demo/p2/Collections.cpp.s

demo/p3/LambdaTest.o: demo/p3/LambdaTest.cpp.o
.PHONY : demo/p3/LambdaTest.o

# target to build an object file
demo/p3/LambdaTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p3/LambdaTest.cpp.o
.PHONY : demo/p3/LambdaTest.cpp.o

demo/p3/LambdaTest.i: demo/p3/LambdaTest.cpp.i
.PHONY : demo/p3/LambdaTest.i

# target to preprocess a source file
demo/p3/LambdaTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p3/LambdaTest.cpp.i
.PHONY : demo/p3/LambdaTest.cpp.i

demo/p3/LambdaTest.s: demo/p3/LambdaTest.cpp.s
.PHONY : demo/p3/LambdaTest.s

# target to generate assembly for a file
demo/p3/LambdaTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p3/LambdaTest.cpp.s
.PHONY : demo/p3/LambdaTest.cpp.s

demo/p4/DesignModel.o: demo/p4/DesignModel.cpp.o
.PHONY : demo/p4/DesignModel.o

# target to build an object file
demo/p4/DesignModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p4/DesignModel.cpp.o
.PHONY : demo/p4/DesignModel.cpp.o

demo/p4/DesignModel.i: demo/p4/DesignModel.cpp.i
.PHONY : demo/p4/DesignModel.i

# target to preprocess a source file
demo/p4/DesignModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p4/DesignModel.cpp.i
.PHONY : demo/p4/DesignModel.cpp.i

demo/p4/DesignModel.s: demo/p4/DesignModel.cpp.s
.PHONY : demo/p4/DesignModel.s

# target to generate assembly for a file
demo/p4/DesignModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p4/DesignModel.cpp.s
.PHONY : demo/p4/DesignModel.cpp.s

demo/p5/ORM.o: demo/p5/ORM.cpp.o
.PHONY : demo/p5/ORM.o

# target to build an object file
demo/p5/ORM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p5/ORM.cpp.o
.PHONY : demo/p5/ORM.cpp.o

demo/p5/ORM.i: demo/p5/ORM.cpp.i
.PHONY : demo/p5/ORM.i

# target to preprocess a source file
demo/p5/ORM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p5/ORM.cpp.i
.PHONY : demo/p5/ORM.cpp.i

demo/p5/ORM.s: demo/p5/ORM.cpp.s
.PHONY : demo/p5/ORM.s

# target to generate assembly for a file
demo/p5/ORM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/demo/p5/ORM.cpp.s
.PHONY : demo/p5/ORM.cpp.s

entity/Animal.o: entity/Animal.cpp.o
.PHONY : entity/Animal.o

# target to build an object file
entity/Animal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Animal.cpp.o
.PHONY : entity/Animal.cpp.o

entity/Animal.i: entity/Animal.cpp.i
.PHONY : entity/Animal.i

# target to preprocess a source file
entity/Animal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Animal.cpp.i
.PHONY : entity/Animal.cpp.i

entity/Animal.s: entity/Animal.cpp.s
.PHONY : entity/Animal.s

# target to generate assembly for a file
entity/Animal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Animal.cpp.s
.PHONY : entity/Animal.cpp.s

entity/AnimalManager.o: entity/AnimalManager.cpp.o
.PHONY : entity/AnimalManager.o

# target to build an object file
entity/AnimalManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/AnimalManager.cpp.o
.PHONY : entity/AnimalManager.cpp.o

entity/AnimalManager.i: entity/AnimalManager.cpp.i
.PHONY : entity/AnimalManager.i

# target to preprocess a source file
entity/AnimalManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/AnimalManager.cpp.i
.PHONY : entity/AnimalManager.cpp.i

entity/AnimalManager.s: entity/AnimalManager.cpp.s
.PHONY : entity/AnimalManager.s

# target to generate assembly for a file
entity/AnimalManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/AnimalManager.cpp.s
.PHONY : entity/AnimalManager.cpp.s

entity/Cat.o: entity/Cat.cpp.o
.PHONY : entity/Cat.o

# target to build an object file
entity/Cat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Cat.cpp.o
.PHONY : entity/Cat.cpp.o

entity/Cat.i: entity/Cat.cpp.i
.PHONY : entity/Cat.i

# target to preprocess a source file
entity/Cat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Cat.cpp.i
.PHONY : entity/Cat.cpp.i

entity/Cat.s: entity/Cat.cpp.s
.PHONY : entity/Cat.s

# target to generate assembly for a file
entity/Cat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Cat.cpp.s
.PHONY : entity/Cat.cpp.s

entity/CatFamily.o: entity/CatFamily.cpp.o
.PHONY : entity/CatFamily.o

# target to build an object file
entity/CatFamily.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/CatFamily.cpp.o
.PHONY : entity/CatFamily.cpp.o

entity/CatFamily.i: entity/CatFamily.cpp.i
.PHONY : entity/CatFamily.i

# target to preprocess a source file
entity/CatFamily.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/CatFamily.cpp.i
.PHONY : entity/CatFamily.cpp.i

entity/CatFamily.s: entity/CatFamily.cpp.s
.PHONY : entity/CatFamily.s

# target to generate assembly for a file
entity/CatFamily.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/CatFamily.cpp.s
.PHONY : entity/CatFamily.cpp.s

entity/Dog.o: entity/Dog.cpp.o
.PHONY : entity/Dog.o

# target to build an object file
entity/Dog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Dog.cpp.o
.PHONY : entity/Dog.cpp.o

entity/Dog.i: entity/Dog.cpp.i
.PHONY : entity/Dog.i

# target to preprocess a source file
entity/Dog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Dog.cpp.i
.PHONY : entity/Dog.cpp.i

entity/Dog.s: entity/Dog.cpp.s
.PHONY : entity/Dog.s

# target to generate assembly for a file
entity/Dog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/Dog.cpp.s
.PHONY : entity/Dog.cpp.s

entity/DogFamily.o: entity/DogFamily.cpp.o
.PHONY : entity/DogFamily.o

# target to build an object file
entity/DogFamily.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/DogFamily.cpp.o
.PHONY : entity/DogFamily.cpp.o

entity/DogFamily.i: entity/DogFamily.cpp.i
.PHONY : entity/DogFamily.i

# target to preprocess a source file
entity/DogFamily.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/DogFamily.cpp.i
.PHONY : entity/DogFamily.cpp.i

entity/DogFamily.s: entity/DogFamily.cpp.s
.PHONY : entity/DogFamily.s

# target to generate assembly for a file
entity/DogFamily.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/DogFamily.cpp.s
.PHONY : entity/DogFamily.cpp.s

entity/TrainAnimal.o: entity/TrainAnimal.cpp.o
.PHONY : entity/TrainAnimal.o

# target to build an object file
entity/TrainAnimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/TrainAnimal.cpp.o
.PHONY : entity/TrainAnimal.cpp.o

entity/TrainAnimal.i: entity/TrainAnimal.cpp.i
.PHONY : entity/TrainAnimal.i

# target to preprocess a source file
entity/TrainAnimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/TrainAnimal.cpp.i
.PHONY : entity/TrainAnimal.cpp.i

entity/TrainAnimal.s: entity/TrainAnimal.cpp.s
.PHONY : entity/TrainAnimal.s

# target to generate assembly for a file
entity/TrainAnimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/TrainAnimal.cpp.s
.PHONY : entity/TrainAnimal.cpp.s

entity/model/User.o: entity/model/User.cpp.o
.PHONY : entity/model/User.o

# target to build an object file
entity/model/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/model/User.cpp.o
.PHONY : entity/model/User.cpp.o

entity/model/User.i: entity/model/User.cpp.i
.PHONY : entity/model/User.i

# target to preprocess a source file
entity/model/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/model/User.cpp.i
.PHONY : entity/model/User.cpp.i

entity/model/User.s: entity/model/User.cpp.s
.PHONY : entity/model/User.s

# target to generate assembly for a file
entity/model/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/entity/model/User.cpp.s
.PHONY : entity/model/User.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/main.cpp.s
.PHONY : main.cpp.s

mapper/UserDao.o: mapper/UserDao.cpp.o
.PHONY : mapper/UserDao.o

# target to build an object file
mapper/UserDao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/mapper/UserDao.cpp.o
.PHONY : mapper/UserDao.cpp.o

mapper/UserDao.i: mapper/UserDao.cpp.i
.PHONY : mapper/UserDao.i

# target to preprocess a source file
mapper/UserDao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/mapper/UserDao.cpp.i
.PHONY : mapper/UserDao.cpp.i

mapper/UserDao.s: mapper/UserDao.cpp.s
.PHONY : mapper/UserDao.s

# target to generate assembly for a file
mapper/UserDao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/mapper/UserDao.cpp.s
.PHONY : mapper/UserDao.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... learning"
	@echo "... CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... cmake-build-debug/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... config/MysqlDb.o"
	@echo "... config/MysqlDb.i"
	@echo "... config/MysqlDb.s"
	@echo "... demo/p1/Polymorphism.o"
	@echo "... demo/p1/Polymorphism.i"
	@echo "... demo/p1/Polymorphism.s"
	@echo "... demo/p2/Collections.o"
	@echo "... demo/p2/Collections.i"
	@echo "... demo/p2/Collections.s"
	@echo "... demo/p3/LambdaTest.o"
	@echo "... demo/p3/LambdaTest.i"
	@echo "... demo/p3/LambdaTest.s"
	@echo "... demo/p4/DesignModel.o"
	@echo "... demo/p4/DesignModel.i"
	@echo "... demo/p4/DesignModel.s"
	@echo "... demo/p5/ORM.o"
	@echo "... demo/p5/ORM.i"
	@echo "... demo/p5/ORM.s"
	@echo "... entity/Animal.o"
	@echo "... entity/Animal.i"
	@echo "... entity/Animal.s"
	@echo "... entity/AnimalManager.o"
	@echo "... entity/AnimalManager.i"
	@echo "... entity/AnimalManager.s"
	@echo "... entity/Cat.o"
	@echo "... entity/Cat.i"
	@echo "... entity/Cat.s"
	@echo "... entity/CatFamily.o"
	@echo "... entity/CatFamily.i"
	@echo "... entity/CatFamily.s"
	@echo "... entity/Dog.o"
	@echo "... entity/Dog.i"
	@echo "... entity/Dog.s"
	@echo "... entity/DogFamily.o"
	@echo "... entity/DogFamily.i"
	@echo "... entity/DogFamily.s"
	@echo "... entity/TrainAnimal.o"
	@echo "... entity/TrainAnimal.i"
	@echo "... entity/TrainAnimal.s"
	@echo "... entity/model/User.o"
	@echo "... entity/model/User.i"
	@echo "... entity/model/User.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mapper/UserDao.o"
	@echo "... mapper/UserDao.i"
	@echo "... mapper/UserDao.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

