// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef SIMPLE_USER_ODB_HXX
#define SIMPLE_USER_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "SimpleUser.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // SimpleUser
  //
  template <>
  struct class_traits< ::SimpleUser >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::SimpleUser >
  {
    public:
    typedef ::SimpleUser object_type;
    typedef ::SimpleUser* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // SimpleUser
  //
  template <typename A>
  struct query_columns< ::SimpleUser, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // username
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    username_type_;

    static const username_type_ username;

    // password
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    password_type_;

    static const password_type_ password;

    // age
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    age_type_;

    static const age_type_ age;

    // update_user
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    update_user_type_;

    static const update_user_type_ update_user;
  };

  template <typename A>
  const typename query_columns< ::SimpleUser, id_mysql, A >::id_type_
  query_columns< ::SimpleUser, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::SimpleUser, id_mysql, A >::username_type_
  query_columns< ::SimpleUser, id_mysql, A >::
  username (A::table_name, "`user_name`", 0);

  template <typename A>
  const typename query_columns< ::SimpleUser, id_mysql, A >::password_type_
  query_columns< ::SimpleUser, id_mysql, A >::
  password (A::table_name, "`password`", 0);

  template <typename A>
  const typename query_columns< ::SimpleUser, id_mysql, A >::age_type_
  query_columns< ::SimpleUser, id_mysql, A >::
  age (A::table_name, "`age`", 0);

  template <typename A>
  const typename query_columns< ::SimpleUser, id_mysql, A >::update_user_type_
  query_columns< ::SimpleUser, id_mysql, A >::
  update_user (A::table_name, "`update_user`", 0);

  template <typename A>
  struct pointer_query_columns< ::SimpleUser, id_mysql, A >:
    query_columns< ::SimpleUser, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::SimpleUser, id_mysql >:
    public access::object_traits< ::SimpleUser >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      unsigned long long id_value;
      my_bool id_null;

      // username_
      //
      details::buffer username_value;
      unsigned long username_size;
      my_bool username_null;

      // password_
      //
      details::buffer password_value;
      unsigned long password_size;
      my_bool password_null;

      // age_
      //
      int age_value;
      my_bool age_null;

      // update_user_
      //
      details::buffer update_user_value;
      unsigned long update_user_size;
      my_bool update_user_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::SimpleUser, id_common >:
    public access::object_traits_impl< ::SimpleUser, id_mysql >
  {
  };

  // SimpleUser
  //
}

#include "SimpleUser-odb.ixx"

#include <odb/post.hxx>

#endif // SIMPLE_USER_ODB_HXX
