/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `user_name` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `age` INT NOT NULL,
  `birthday` DATETIME NOT NULL,
  `create_time` DATETIME NOT NULL,
  `create_user` TEXT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user` TEXT NOT NULL)
 ENGINE=InnoDB;

