/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `simple_user`;

CREATE TABLE `simple_user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `user_name` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `age` INT NOT NULL,
  `update_user` TEXT NOT NULL)
 ENGINE=InnoDB;

