// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "../../include/User-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // User
  //

  struct access::object_traits_impl< ::User, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::User, id_mysql >::id_type
  access::object_traits_impl< ::User, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long int,
          mysql::id_longlong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // username_
    //
    if (t[1UL])
    {
      i.username_value.capacity (i.username_size);
      grew = true;
    }

    // password_
    //
    if (t[2UL])
    {
      i.password_value.capacity (i.password_size);
      grew = true;
    }

    // age_
    //
    t[3UL] = 0;

    // birthday_
    //
    t[4UL] = 0;

    // create_time_
    //
    t[5UL] = 0;

    // create_user_
    //
    if (t[6UL])
    {
      i.create_user_value.capacity (i.create_user_size);
      grew = true;
    }

    // update_time_
    //
    t[7UL] = 0;

    // update_user_
    //
    if (t[8UL])
    {
      i.update_user_value.capacity (i.update_user_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // username_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.username_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.username_value.capacity ());
    b[n].length = &i.username_size;
    b[n].is_null = &i.username_null;
    n++;

    // password_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.password_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.password_value.capacity ());
    b[n].length = &i.password_size;
    b[n].is_null = &i.password_null;
    n++;

    // age_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.age_value;
    b[n].is_null = &i.age_null;
    n++;

    // birthday_
    //
    b[n].buffer_type = MYSQL_TYPE_DATETIME;
    b[n].buffer = &i.birthday_value;
    b[n].is_null = &i.birthday_null;
    n++;

    // create_time_
    //
    b[n].buffer_type = MYSQL_TYPE_DATETIME;
    b[n].buffer = &i.create_time_value;
    b[n].is_null = &i.create_time_null;
    n++;

    // create_user_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.create_user_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.create_user_value.capacity ());
    b[n].length = &i.create_user_size;
    b[n].is_null = &i.create_user_null;
    n++;

    // update_time_
    //
    b[n].buffer_type = MYSQL_TYPE_DATETIME;
    b[n].buffer = &i.update_time_value;
    b[n].is_null = &i.update_time_null;
    n++;

    // update_user_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.update_user_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.update_user_value.capacity ());
    b[n].length = &i.update_user_size;
    b[n].is_null = &i.update_user_null;
    n++;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      long int const& v =
        o.id_;

      bool is_null (false);
      mysql::value_traits<
          long int,
          mysql::id_longlong >::set_image (
        i.id_value, is_null, v);
      i.id_null = is_null;
    }

    // username_
    //
    {
      ::std::string const& v =
        o.username_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.username_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.username_value,
        size,
        is_null,
        v);
      i.username_null = is_null;
      i.username_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.username_value.capacity ());
    }

    // password_
    //
    {
      ::std::string const& v =
        o.password_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.password_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.password_value,
        size,
        is_null,
        v);
      i.password_null = is_null;
      i.password_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.password_value.capacity ());
    }

    // age_
    //
    {
      int const& v =
        o.age_;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.age_value, is_null, v);
      i.age_null = is_null;
    }

    // birthday_
    //
    {
      ::time_t const& v =
        o.birthday_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_image (
        i.birthday_value, is_null, v);
      i.birthday_null = is_null;
    }

    // create_time_
    //
    {
      ::time_t const& v =
        o.create_time_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_image (
        i.create_time_value, is_null, v);
      i.create_time_null = is_null;
    }

    // create_user_
    //
    {
      ::std::string const& v =
        o.create_user_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.create_user_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.create_user_value,
        size,
        is_null,
        v);
      i.create_user_null = is_null;
      i.create_user_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.create_user_value.capacity ());
    }

    // update_time_
    //
    {
      ::time_t const& v =
        o.update_time_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_image (
        i.update_time_value, is_null, v);
      i.update_time_null = is_null;
    }

    // update_user_
    //
    {
      ::std::string const& v =
        o.update_user_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.update_user_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.update_user_value,
        size,
        is_null,
        v);
      i.update_user_null = is_null;
      i.update_user_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.update_user_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long int& v =
        o.id_;

      mysql::value_traits<
          long int,
          mysql::id_longlong >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // username_
    //
    {
      ::std::string& v =
        o.username_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.username_value,
        i.username_size,
        i.username_null);
    }

    // password_
    //
    {
      ::std::string& v =
        o.password_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.password_value,
        i.password_size,
        i.password_null);
    }

    // age_
    //
    {
      int& v =
        o.age_;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i.age_value,
        i.age_null);
    }

    // birthday_
    //
    {
      ::time_t& v =
        o.birthday_;

      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_value (
        v,
        i.birthday_value,
        i.birthday_null);
    }

    // create_time_
    //
    {
      ::time_t& v =
        o.create_time_;

      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_value (
        v,
        i.create_time_value,
        i.create_time_null);
    }

    // create_user_
    //
    {
      ::std::string& v =
        o.create_user_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.create_user_value,
        i.create_user_size,
        i.create_user_null);
    }

    // update_time_
    //
    {
      ::time_t& v =
        o.update_time_;

      mysql::value_traits<
          ::time_t,
          mysql::id_datetime >::set_value (
        v,
        i.update_time_value,
        i.update_time_null);
    }

    // update_user_
    //
    {
      ::std::string& v =
        o.update_user_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.update_user_value,
        i.update_user_size,
        i.update_user_null);
    }
  }

  void access::object_traits_impl< ::User, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long int,
          mysql::id_longlong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::User, id_mysql >::persist_statement[] =
  "INSERT INTO `User` "
  "(`id`, "
  "`user_name`, "
  "`password`, "
  "`age`, "
  "`birthday`, "
  "`create_time`, "
  "`create_user`, "
  "`update_time`, "
  "`update_user`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::User, id_mysql >::find_statement[] =
  "SELECT "
  "`User`.`id`, "
  "`User`.`user_name`, "
  "`User`.`password`, "
  "`User`.`age`, "
  "`User`.`birthday`, "
  "`User`.`create_time`, "
  "`User`.`create_user`, "
  "`User`.`update_time`, "
  "`User`.`update_user` "
  "FROM `User` "
  "WHERE `User`.`id`=?";

  const char access::object_traits_impl< ::User, id_mysql >::update_statement[] =
  "UPDATE `User` "
  "SET "
  "`user_name`=?, "
  "`password`=?, "
  "`age`=?, "
  "`birthday`=?, "
  "`create_time`=?, "
  "`create_user`=?, "
  "`update_time`=?, "
  "`update_user`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::User, id_mysql >::erase_statement[] =
  "DELETE FROM `User` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::User, id_mysql >::query_statement[] =
  "SELECT "
  "`User`.`id`, "
  "`User`.`user_name`, "
  "`User`.`password`, "
  "`User`.`age`, "
  "`User`.`birthday`, "
  "`User`.`create_time`, "
  "`User`.`create_user`, "
  "`User`.`update_time`, "
  "`User`.`update_user` "
  "FROM `User`";

  const char access::object_traits_impl< ::User, id_mysql >::erase_query_statement[] =
  "DELETE FROM `User`";

  const char access::object_traits_impl< ::User, id_mysql >::table_name[] =
  "`User`";

  void access::object_traits_impl< ::User, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::User, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::User, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::User, id_mysql >::pointer_type
  access::object_traits_impl< ::User, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::User, id_mysql >::object_type >
  access::object_traits_impl< ::User, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::User, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
